coverage:
  status:
    project:
      default: false
      tests:
        target: 95%
        paths:
          - "tests/"
      package:
        target: 80%
        paths:
          - "!tests/"
    patch:
      default: false
      tests:
        target: 100%
        paths:
          - "tests/"
      package:
        target: 80%
        paths:
          - "!tests/"
