name: Dependency Review
on:
  pull_request:
    branches:
      - master
      - release*
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
